### PR TITLE
Minor, just to create a difference in bracnhes

### PR DESCRIPTION
**Pull request by asiimwedismas**
Milestone 6: Friendships v2 
Implement friendships with 2 rows for mutual friendship

### CODE REVIEW

**Comment by asiimwedismas** [comment]
Am pretty sure we both have absolutely zero ideas on what to do in this milestone as we already implemented the method to confirm friendships in friendship v1

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Dismas Asiimwe & Houda Cherkaoui** 
Nice job with your first submission :muscle:  :muscle: 
Your page meets most of the requirements :clap: :clap: :clap:  
We still need to fix some details:

- [x] you have a typo in your user model file, line 39 change "destory" for "destroy"
- [x] remove commented code in the "new.html.erb" file
- [x] In the Usage section of your README file, explain all the steps to run the project (e.g. run bundle install)

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- The functionalities of these 👇  methods in the `user` model 
  - pending_friends
  - friend_requests

...can be implemented through the database i.e., you can make the database do the work instead of relying on ruby (processing objects in application memory), as the database was created to store and query data it is always more efficient than ruby.

Here is an example:

```ruby
# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

You can find more details about using scopes [here](https://guides.rubyonrails.org/association_basics.html#scopes-for-has-many)

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

#### [OPTIONAL]

- Your PR title could be improved to make it professional. Remember, however, small the change is, the PR title should be able to give an idea about the change to the reviewer, kinda like the title of a news article 😉 .
- Consider moving the friendship methods from your user model to the friendship model. The user model is all about the user. Friendship is a whole different *idea*. Sure, friendship happens between two users, but does it really *define* a user? Here is a different point of view - a "user" `has_many :friendships, dependent: :destroy` but **NOT** vice-versa.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Comment by asiimwedismas** [comment]
> ### Status: Changes Required ♻️
> **Hello Dismas Asiimwe & Houda Cherkaoui**
> Nice job with your first submission 💪 💪
> Your page meets most of the requirements 👏 👏 👏
> We still need to fix some details:
> 
> * [x]  you have a typo in your user model file, line 39 change "destory" for "destroy"
> * [x]  remove commented code in the "new.html.erb" file
> * [x]  In the Usage section of your README file, explain all the steps to run the project (e.g. run bundle install)
> 
> Please request another review once you are ready! 👍
> 
> Happy coding ☺️
> 
> Oscar Andrés Russi Porras

**Review by lucasmazo32 — APPROVED** [review]
# Project approved :rocket:

#### Great job!

#### Your project looks great!

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

**Pull request merged**
